"""
Revision script template
"""
from alembic import op
import sqlalchemy as sa

revision = '898e08bf6eff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade operations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    """Downgrade operations go here."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
